CREATE OR REPLACE FUNCTION test_log() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO log (data, operacao) VALUES(CURRENT_DATE, 'D');
  RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

DROP TRIGGER IF EXISTS testlogs ON aluno;

CREATE TRIGGER testlogs
  AFTER DELETE OR UPDATE ON aluno
  FOR EACH ROW
  EXECUTE FUNCTION test_log();

